on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Wait
        run: sleep 5
  profit-a: &profit-job
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: noop
  profit-b: *profit-job
  profit-c: *profit-job
  profit-d: *profit-job
  profit-e: *profit-job
  profit-f: *profit-job
  profit-g: *profit-job
  profit-h: *profit-job
  profit-i: *profit-job
  profit-j: *profit-job
  profit-k: *profit-job
  profit-l: *profit-job
  profit-m: *profit-job
  profit-n: *profit-job
  profit-o: *profit-job
  profit-p: *profit-job
  profit-q: *profit-job
  profit-r: *profit-job
  profit-s: *profit-job
  profit-t: *profit-job
  profit-u: *profit-job
  profit-v: *profit-job
  profit-w: *profit-job
  profit-x: *profit-job
  profit-y: *profit-job
  profit-z: *profit-job
